/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaJNIExample */

#ifndef _Included_JavaJNIExample
#define _Included_JavaJNIExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaJNIExample
 * Method:    processAccount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JavaJNIExample_processAccount
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
